
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           29259
     no. of nonzeroes in lower triangle of a =         1015848
     no. of nonzeroes in the factor l        =         5426534
     ratio of nonzeroes in factor (min/max)  =          0.8635
     number of super nodes                   =            1044
     maximum order of a front matrix         =             519
     maximum size of a front matrix          =          134940
     maximum size of a front trapezoid       =           78324
     no. of floating point ops for factor    =      1.1241D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7308
     ratio of allocated memory (max/min)     =          1.1166
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002015
     time (cpu & wall) for ordering          =        0.046875        0.060539
     time (cpu & wall) for other matrix prep =        0.015625        0.012716
     time (cpu & wall) for value input       =        0.015625        0.004291
     time (cpu & wall) for matrix distrib.   =        0.031250        0.037173
     time (cpu & wall) for numeric factor    =        0.156250        0.153811
     computational rate (gflops) for factor  =        7.194071        7.308125
     time (cpu & wall) for numeric solve     =        0.031250        0.020500
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69008.        1. MB
                95-   1         98304.        1. MB         67668.        1. MB
                95-   2         98304.        1. MB         75321.        1. MB
                95-   3         98304.        1. MB         68513.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        280510.        2. MB


  Solver Memory allocated on core    0       =       24.004 MB
  Solver Memory allocated on core    1       =       22.716 MB
  Solver Memory allocated on core    2       =       23.841 MB
  Solver Memory allocated on core    3       =       21.498 MB
  Total Solver Memory allocated by all cores =       92.060 MB

