
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          227880
     no. of nonzeroes in lower triangle of a =         8097381
     no. of nonzeroes in the factor l        =        61987187
     ratio of nonzeroes in factor (min/max)  =          0.6924
     number of super nodes                   =            8615
     maximum order of a front matrix         =            1515
     maximum size of a front matrix          =         1148370
     maximum size of a front trapezoid       =          781011
     no. of floating point ops for factor    =      2.7977D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.5316
     ratio of allocated memory (max/min)     =          1.3178
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.046875        0.035440
     time (cpu & wall) for ordering          =        0.578125        0.595109
     time (cpu & wall) for other matrix prep =        0.093750        0.098055
     time (cpu & wall) for value input       =        0.062500        0.062499
     time (cpu & wall) for matrix distrib.   =        0.250000        0.297603
     time (cpu & wall) for numeric factor    =        1.343750        1.443129
     computational rate (gflops) for factor  =       20.819961       19.386225
     time (cpu & wall) for numeric solve     =        0.062500        0.063631
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        622592.        5. MB        599357.        5. MB
                95-   1        524288.        4. MB        507342.        4. MB
                95-   2        491520.        4. MB        478679.        4. MB
                95-   3        688128.        5. MB        656746.        5. MB

                -------     ----------     --------     ----------     --------
                Totals:       2326528.       18. MB       2242124.       17. MB


  Solver Memory allocated on core    0       =      242.424 MB
  Solver Memory allocated on core    1       =      191.839 MB
  Solver Memory allocated on core    2       =      202.663 MB
  Solver Memory allocated on core    3       =      252.797 MB
  Total Solver Memory allocated by all cores =      889.722 MB

