
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          227268
     no. of nonzeroes in lower triangle of a =         8075142
     no. of nonzeroes in the factor l        =        62419818
     ratio of nonzeroes in factor (min/max)  =          0.7683
     number of super nodes                   =            8569
     maximum order of a front matrix         =            1695
     maximum size of a front matrix          =         1437360
     maximum size of a front trapezoid       =          973194
     no. of floating point ops for factor    =      2.9523D+10
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.6309
     ratio of allocated memory (max/min)     =          1.2482
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.031250        0.027339
     time (cpu & wall) for ordering          =        0.546875        0.611460
     time (cpu & wall) for other matrix prep =        0.093750        0.104979
     time (cpu & wall) for value input       =        0.093750        0.092063
     time (cpu & wall) for matrix distrib.   =        0.250000        0.291168
     time (cpu & wall) for numeric factor    =        1.531250        1.891115
     computational rate (gflops) for factor  =       19.280051       15.611203
     time (cpu & wall) for numeric solve     =        0.062500        0.053997
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        491520.        4. MB        461682.        4. MB
                95-   1        688128.        5. MB        657266.        5. MB
                95-   2        589824.        4. MB        588674.        4. MB
                95-   3        557056.        4. MB        528719.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:       2326528.       18. MB       2236341.       17. MB


  Solver Memory allocated on core    0       =      200.624 MB
  Solver Memory allocated on core    1       =      248.155 MB
  Solver Memory allocated on core    2       =      245.678 MB
  Solver Memory allocated on core    3       =      198.817 MB
  Total Solver Memory allocated by all cores =      893.274 MB

